### PR TITLE
Add impl HugrView for SubHugr

### PR DESCRIPTION
**Pull request by doug-q**
No tests as of yet

### CODE REVIEW

**Comment by doug-q** [comment]
@zrho Can you review?

**Comment by lmondada** [comment]
Oh this is awsome!!! Thank you so much @doug-q !! Will have a look this afternoon

**Review by lmondada — COMMENTED** [review]
Hi @doug-q, thanks a lot for the work, it's great!!

We've got an issue whereby the datastructure that we would need from `portgraph`, i.e. something that traverses both the sibling subgraph + descendants nodes within does not exist.

Your code makes me think that probably the best solution for the moment would be to change the semantics of `SubHugr` to only cover the sibling graph itself and not its descendants. In that case this code would work.

This is good enough for my current needs.

I see two options to proceed:
- You merge this in as is right now, and I take care of changing `SubHugr` in #336
- You keep these changes and apply them as a separate PR once I've merged in #336.

Choose the one that you prefer, both work for me. I personally think option 2 will give you more credit for your work, but it will be slightly more work for you to resolve the merge conflicts -- the work should be minimal though.

Thanks a lot again for everything!

**Comment by doug-q** [comment]
Thanks for the review. If you are happy changing semantics of SubHugr, go ahead. I'm ignorant as to whether that's a good idea. I'll post another PR once your work is merged

**Comment by lmondada** [comment]
Ok, perfect. Should be merged in later today hopefully!

**Review by zrho — APPROVED** [review]

**Pull request closed without merging**
