### PR TITLE
There is no alternative.

### PR DESCRIPTION
**Pull request by cqc-alec**
Or is there?

### CODE REVIEW

**Comment by acl-cqc** [comment]
This is not intended to suggest that any alternative to `TailLoop` exists right now. But I discussed a while back with @ss2165 how there are a great many alternative forms that we *could* have - typically, these allow to express more loops than `TailLoop` (loops that would otherwise have to be built as `Cfg` nodes), but are more complex to use.

I think we will only really see the motivation for this when we have a decent body/corpus of programs written in the Hugr, so it's not a decision we can take right now. @ss2165 agreed? But perhaps the doc just needs to be clearer that it's a note for the future rather than a description of the present - before we switched to `.md` it used to be "boxed out" so is there anything like that we can do in .md?

**Comment by ss2165** [comment]
I wonder if it might be left as an issue for the future rather than a discussion in the spec?

**Comment by cqc-alec** [comment]
Yeah I'm happy to create an issue for this. I think there is benefit to making this document a concise description of our current proposal. @acl-cqc would you be OK with moving it out to a separate issue?

**Comment by acl-cqc** [comment]
Yes, absolutely. (An issue or a discussion? - neither of which were being used when we wrote this in the spec)

**Comment by cqc-alec** [comment]
> Yes, absolutely. (An issue or a discussion? - neither of which were being used when we wrote this in the spec)

Probably a discussion actually.

**Comment by cqc-alec** [comment]
#216

**Review by acl-cqc — APPROVED** [review]

**Comment by acl-cqc** [comment]
Ok, thanks!

**Pull request merged**
